application: freebase-delphi
version: multi-iframe
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: api.app
- url: /apis/.*
  script: api.app
- url: /client/delphi.js
  script: client.app
- url: /
  static_dir: static/
  login: required
