application: freebase-delphi
version: simple
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  login: required
- url: /question/.*
  static_files: static/index.html
  upload: static/index.html
  login: required
- url: /apis/.*
  script: api.app
  login: required
- url: /client/delphi.js
  script: client.app
- url: /
  static_dir: static/
  login: required
